safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:    /
url: http://localhost:4000

source:      ./_source
destination: ./site
plugins:     ./_source/_plugins

future:      true
lsi:         false
pygments:    false
markdown:    maruku
permalink:   pretty

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex