title: Caio Gondim
email: me@caiogondim.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caiogondim.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: caio_gondim
github_username:  caiogondim
permalink: /post/:title
collections:
  photos_2016_nyc:
    output: true
    permalink: /photo/nyc-2016/:title
  photos_2017_nyc:
    output: true
    permalink: /photo/nyc-2017/:title
  photos_2017_times_square:
    output: true
    permalink: /photo/times-square-2017/:title

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
