title: Caio Gondim
email: me@caiogondim.com
description: >
  Caio Gondim's personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caiogondim.com"
twitter_username: caio_gondim
github_username: caiogondim
permalink: /post/:title
collections:
  photos_2016_nyc:
    output: true
    permalink: /photo/nyc-2016/:title
  photos_2017_nyc:
    output: true
    permalink: /photo/nyc-2017/:title
  photos_2017_times_square:
    output: true
    permalink: /photo/times-square-2017/:title
  photos_2017_mauna_kea_observatories:
    output: true
    permalink: /photo/mauna-kea-observatories-2017/:title
  photos-2017-hawaii:
    output: true
    permalink: /photo/hawaii-2017/:title

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
