import Shell from '../components/shell'
import Header from '../components/header'
import Content from '../components/content'
import PageIntro from '../components/page-intro'
import YearSeparator from '../components/year-separator'
import LinkTargetBlank from '../components/link-target-blank'

function Projects () {
  return (
    <Shell>
      <Header pageName="/ Projects" />
      <Content>
        <div>
          <PageIntro>
            Some of the projects I was proud to be a part of.
          </PageIntro>

          <YearSeparator>2019</YearSeparator>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/superstylin">superstylin</LinkTargetBlank></h3>
            <p>
              Superstylin is a drop-in CSS library that serves as a better CSS default for your HTML.
            </p>
          </section>

          <YearSeparator>2018</YearSeparator>

          <section>
            <h3><LinkTargetBlank href="https://github.com/video-dev/can-autoplay">can-autoplay.js</LinkTargetBlank></h3>
            <p>
              The auto-play feature detection in HTMLMediaElement (<code>&lt;audio&gt;</code> or <code>&lt;video&gt;</code>).
              Used in production by The New York Times, Vimeo, ...
            </p>
          </section>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/city-state.js">city-state.js</LinkTargetBlank></h3>
            <p>
              Observable and encapsulated state management for React.
            </p>
          </section>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/webpack-conditional-loader">webpack-conditional-loader</LinkTargetBlank></h3>
            <p>
              Inspired by C conditionals directive, conditional loader decides if a given block should be included in the final bundle.
              Useful for removing instrumentation code and making your final production bundle smaller (therefore faster).
            </p>
          </section>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/react-with-dimensions">react-with-dimensions</LinkTargetBlank></h3>
            <p>
              React decorator to receive dimensions props generated by <code>ResizeObserver</code>.
            </p>
          </section>

          <YearSeparator>2017</YearSeparator>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/fast-memoize.js">fast-memoize.js</LinkTargetBlank></h3>
            <p>
              An attempt to make the fastest possible memoization library in JavaScript that supports N arguments.
            </p>
          </section>

          <section>
            <h3><LinkTargetBlank href="https://github.com/caiogondim/redux-whenever.js">redux-whenever.js</LinkTargetBlank></h3>
            <p>
              Subscribe to a state subtree (or leaf) and run callbacks whenever it evaluates to a given value.
            </p>
          </section>

          <YearSeparator>2015</YearSeparator>

          <section>
            <h3>Front in Amsterdam</h3>
            <p>
              Front in Amsterdam is a non-profit international conference
              organised by front-end enthusiasts. An organisation working to
              promote front-end technologies such as HTML5, CSS3, JavaScript,
              and UX Design.
            </p>
          </section>

          <YearSeparator>2012</YearSeparator>

          <section>
            <h3>Volunteer work in India</h3>
            <p>
              Lived in New Delhi, India, for two months to help the
              Commonwealth Human Rights Initiative to build their new website
              and experience a new culture.
            </p>
          </section>

          <section>
            <h3><LinkTargetBlank href="http://loopinfinito.com.br">loopinfinito.com.br</LinkTargetBlank></h3>
            <p>
              Blog about web development written in portuguese for the Brazilian community.
            </p>
          </section>

        </div>
      </Content>
    </Shell>
  )
}

export default Projects
